[package]
name = "artifacter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
env_logger = "0.10.0"
localization = "0.1.3"
log = "0.4.20"
serde_json = "1.0.107"
sqlx = { version = "0.7.2", features = ["tls-rustls", "runtime-tokio", "postgres"] }
tokio = { version = "1.33.0", features = ["rt", "rt-multi-thread", "macros"] }

[dependencies.reqwest]
workspace = true

[dependencies.poise]
git = "https://github.com/serenity-rs/poise"
branch = "serenity-next"

[build-dependencies]
localization-build = "0.1.3"
